### ISSUE TITLE
is it ready to use in production

### ISSUE THREAD

**Issue by LabN36** [ClickerMonkey/SemanticUI-Angular#33]
Hey Thanks for the awesome work i really like it.

i just want to know whether one should use this in production or not and also the the roadmaps for this work.

i found this is the only library that supports angular 1 with semantic ui in well manner.

Thanks,
Rishabh

**Comment by ClickerMonkey** [comment]
I've used it in production for a few products. I would say this works 99% as expected - sometimes there's odd behavior around the dropdown. 

There is no roadmap at the moment to ensure that this library keeps up with the changes to Semantic UI - however since this library utilizes the SUI JS code - everything should continue to work okay.

Sometime in the future, if someone else plans to - or If I need to, some of the directives will be updated to better integrate into angular - utilizing directives like ngModel and it's associates.

**Comment by LabN36** [comment]
okay thanks for the info. one more thing i want to ask what versions it supports for IE and other browsers.

**Comment by ClickerMonkey** [comment]
Depends on the version of angular and Semantic UI you are using - you'll have to find which versions and see for yourself on their websites.

**Comment by LabN36** [comment]
alright, thanks for support.
